### PR TITLE
Fixes issues that I had in my PR at #1

### PR DESCRIPTION
**Pull request by lukewestby**

### CODE REVIEW

**Comment by nraboy** [comment]
Thanks for contributing @lukewestby.  Definitely feel free to continue.  My goal is for this to become a pretty awesome wrapper for AngularJS.

**Comment by nraboy** [comment]
Also, would you like to document testing in the README for the things you added?

**Comment by lukewestby** [comment]
Sure thing. I'll do that when I get home tonight, and I'll also start writing some unit tests. Thanks!

**Comment by nraboy** [comment]
Awesome!  Thanks Luke

**Comment by lukewestby** [comment]
Would you prefer PRs to be submitted against the development branch moving forward?

**Comment by nraboy** [comment]
I am not married to the idea.  It was just something that became a habit of mine so I don't end up breaking the master for users.

What are your opinions?

**Comment by lukewestby** [comment]
I think that's the way to go as well, it definitely makes it easier to tag versions and whatnot. I'll submit against development in the future.

**Pull request merged**
